version: "3.8"

services:
  tasks-management:
    build:
      context: ./tasks-management
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/task_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - task-management-network

  task-management-front:
    build:
      context: ./task-management-front
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - tasks-management
    networks:
      - task-management-network

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=task_management
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - task-management-network

networks:
  task-management-network:
    driver: bridge

volumes:
  postgres-data:
